### PR TITLE
feat: add reorg support

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

This PR aims to handle reorgs where they are detected and addressed by rolling back data.

Closes: https://github.com/snapshot-labs/workflow/issues/28

## Test plan
- Apply diff from below (adds support for Blast API and increases interval to catch reorgs)
- Run checkpoint-template `sekhmet/evm` branch with Gnosis Chain API and pretty fresh block.
- Wait for reorg (https://gnosisscan.io/blocks_forked) it's gotten a bit infrequent currently.
- See logs that it was detected, resolved and handled.

```diff
diff --git a/src/checkpoint.ts b/src/checkpoint.ts
index ccba51b..248f971 100644
--- a/src/checkpoint.ts
+++ b/src/checkpoint.ts
@@ -24,7 +24,7 @@ const BLOCK_RELOAD_MIN_RANGE = 10;
 const BLOCK_PRELOAD_STEP = 100;
 const BLOCK_PRELOAD_TARGET = 10;
 const BLOCK_PRELOAD_OFFSET = 50;
-const DEFAULT_FETCH_INTERVAL = 2000;
+const DEFAULT_FETCH_INTERVAL = 500;
 
 export default class Checkpoint {
   public config: CheckpointConfig;
diff --git a/src/providers/evm/provider.ts b/src/providers/evm/provider.ts
index 427c09b..68f4aac 100644
--- a/src/providers/evm/provider.ts
+++ b/src/providers/evm/provider.ts
@@ -63,7 +63,6 @@ export class EvmProvider extends BaseProvider {
       ]);
 
       if (block === null) {
-        this.log.info({ blockNumber: blockNum }, 'block not found');
         throw new BlockNotFoundError();
       }
 
@@ -72,6 +71,14 @@ export class EvmProvider extends BaseProvider {
         throw new ReorgDetectedError();
       }
     } catch (e) {
+      if (
+        e instanceof BlockNotFoundError ||
+        ((e as any).code === 'SERVER_ERROR' && (e as any).error.code === -32001)
+      ) {
+        this.log.info({ blockNumber: blockNum }, 'block not found');
+        throw new BlockNotFoundError();
+      }
+
       this.log.error({ blockNumber: blockNum, err: e }, 'getting block failed... retrying');
       throw e;
     }
```

It's annoying to test, I tested it in more detailed way testing recovery + entities being adjusted, but had to patch a lots of code to fake it.

### CODE REVIEW

**Comment by bonustrack** [comment]
Wiktor making `🐋 X-Large` task looks `🦔 Tiny`

**Comment by bonustrack** [comment]
FYI mainnet have plenty of reorgs happening https://etherscan.io/blocks_forked

**Comment by Sekhmet** [comment]
I don't think it's nearly enough frequent to understand what is going on and make sure it's working, Gnosis chain looks to have way more (few every hour) but I think it might be too little as well.

**Comment by bonustrack** [comment]
@Sekhmet On EVM chain do you watch for pending transactions? I didn't knew it was possible from the RPC. Anyhow it's fine disabling this option on EVM chain.

**Comment by Sekhmet** [comment]
We have "processPoll" handling but it's broken as we look at `latest` instead of `pending` block.

**Comment by Sekhmet** [comment]
> For some reason at the block 36534546 (30 blocks later) it stopped to sync with this error in loop:

This looks like it's some error from Blast API with format we didn't expect, but this code is not commited, only used in the diff I submitted for testing, so should be fine.

**Pull request merged**
