### PR TITLE
feat: detect events and generic config changes

### PR DESCRIPTION
**Pull request by Sekhmet**
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/232
Closes: https://github.com/checkpoint-labs/checkpoint/issues/198

This PR adds verification that tracked events didn't change.

## Test plan

- Start the server normally so start checksum gets persisted.
- Do some change in the config that you expect that should be detected (writer/abi names are not considered as they are user defined).
- Start the server. You get error message.
- Set `resetOnConfigChange` to true in options, start server again, it continues.
- Remove this option, start server again, it works.

### CODE REVIEW

**Comment by bonustrack** [comment]
Tried but `resetMetadata` doesn't work for some reason, I can see the table is not cleared 
image

**Comment by Sekhmet** [comment]
Good catch, it was unrelated to those PRs, submitted PR with a fix and rebased this one on top of it to make it testable: https://github.com/checkpoint-labs/checkpoint/pull/232

**Comment by bonustrack** [comment]
Just tested and noticed that when I remove an event, it doesn't get detected, it only show the error message if I add a new event.

**Comment by Sekhmet** [comment]
@bonustrack I couldn't reproduce this issue directly, but I've found different bug, can you check if you still have this issue?
If yes, make sure you are not calling `resetMetadata` or don't have `resetOnConfigChange` set.

**Comment by bonustrack** [comment]
It works for me now

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
